### ISSUE TITLE
Android Date expired bug

### ISSUE THREAD

**Issue by soundsnow** [RadratSoftworks/nofun#4]
Date/Time
Android: 2007-01-01 to 2037-12-31
Windows: 19xx-xx-xx to 2xxx-xx-xx
Mophun: Before Android

An example: CourierBob.mpn
For Android System Settings, that's impossible!

Delete Unity Splash Screen files/codes for file size
Pure Black Theme/Background for OLED screens
Vulkan/OpenGL ES/Software Video Render
SonyEricsson keys: A B
8-way D-Pad
Phone keys: 1 2 3 4 5 6 7 8 9 0 * # Call Decline L R Fire Up Down Left Right
2D default resolution: 128x160
3D default resolution: 240x320
Android: open mpn in-app file picker
2 Tabs game lists
Tab1 List: 2D
Tab2 List: 3D

CI Workflow
6 hours bugs
Node.js warnings
Android different signatures: uninstall 1.0 install 1.1 uninstall 1.1 install 1.2

@pent0 don't reply this is closed

**Comment by pent0** [comment]
???
